version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: psycare_postgres
    environment:
      POSTGRES_DB: psycaredb
      POSTGRES_USER: psycareuser
      POSTGRES_PASSWORD: psypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
